<?php require ($_SERVER['DOCUMENT_ROOT'].'/crossroads/includes/config.php'); ?>
<!DOCTYPE html>
<html lang="en">
<head>
	
	<?php include_once $_SERVER['DOCUMENT_ROOT'].$webPath.'/includes/gtm-head.php';?>


	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width">
	<meta name="robots" content="noindex, follow" />

	
	<title>Page Not Found - <?php echo $config['ClinicName']; ?></title>
	<meta name="description" content="Page Not Found - <?php echo $config['ClinicName']; ?>">
	<meta name="author" content="Dentalook">

	<!-- Facebook Meta Tags -->
	<meta property="og:url" content="https://crossroadsdental.ca/test">
	<meta property="og:type" content="website">
	<meta property="og:title" content="Page Not Found - <?php echo $config['ClinicName']; ?>">
	<meta property="og:description" content="Page Not Found - <?php echo $config['ClinicName']; ?>">
	<meta property="og:image" content="https://crossroadsdental.ca/test/assets/images/openGraph/homepage-og.png">
  
	<!-- Twitter Meta Tags -->
	<meta name="twitter:card" content="summary_large_image">
	<meta property="twitter:domain" content="dentalook.ca">
	<meta property="twitter:url" content="https://crossroadsdental.ca/test">
	<meta name="twitter:title" content="Page Not Found - <?php echo $config['ClinicName']; ?>">
	<meta name="twitter:description" content="Page Not Found - <?php echo $config['ClinicName']; ?>">
	<meta name="twitter:image" content="https://crossroadsdental.ca/test/assets/images/openGraph/homepage-og.png">

<?php include_once $_SERVER['DOCUMENT_ROOT'].$webPath.'/includes/css-vendors.php';?>
	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<?php include_once $_SERVER['DOCUMENT_ROOT'].$webPath.'/includes/structured-data.php';?>
</head>

<body class="shop-page">
<?php include_once $_SERVER['DOCUMENT_ROOT'].$webPath.'/includes/gtm-body.php';?>
	<?php include_once $_SERVER['DOCUMENT_ROOT'].$webPath.'/includes/header.php';?>
	<!--page content -->

	<!--section-->
	<div class="page-content">
		<!--section-->
		<div class="section mt-0">
			<div class="breadcrumbs-wrap">
				<div class="container">
					<div class="breadcrumbs">
						<a href="">Home</a>
						<span>Page Not Found</span>
					</div>
				</div>
			</div>
		</div>
		<!--//section-->
		<!--section-->
		<div class="section page-content-first">
			<div class="container">
				<div class="text-center mb-2  mb-md-3 mb-lg-4">
					<div class="h-sub theme-color">Page Not Found</div>
					<h1 class="orange-color">Oops! We cannot find the page you were looking for.</h1>
					<div class="">Please click on the link below to go back to the homepage or use the menu above.
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row">
					<div class="col text-center">
						<img src="<?php echo $root; ?>assets/images/page-not-found.jpg" alt="Page Not Found">
						<p class="mb-4">
							<div class="cta-book mb-5">
								<a href="<?php echo $root; ?>" class="btn cta-call"><i class="icon-right-arrow"></i><span>Back to Homepage</span><i class="icon-right-arrow"></i></a>
								<a aria-label="Link to Booking an Appointment" href="<?php  echo $config['ClinicBookingLink']; ?>" class="btn btn-header"><i class="icon-right-arrow"></i><span>Book
										Appointment</span><i class="icon-right-arrow"></i></a>
							</div>
						</p>
					</div>
				</div>
			</div>
		</div>
		<!--//section-->

	</div>
			<!--//section-->
	
	<!--//page content -->
	
	<?php include_once $_SERVER['DOCUMENT_ROOT'].$webPath.'/includes/footer.php';?>
	 <div class="backToTop js-backToTop">
		<i class="icon icon-up-arrow"></i>
	</div>
	 
	<?php include_once $_SERVER['DOCUMENT_ROOT'].$webPath.'/includes/js-vendors.php';?>

<?php include_once $_SERVER['DOCUMENT_ROOT'].$webPath.'/includes/zoho.php';?>

</html>