<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Organization",
      "image": "https://crossroadsdental.ca/assets/images/logo.png",
      "url": "https://crossroadsdental.ca",
      "logo": "https://crossroadsdental.ca/assets/images/logo.png",
      "name": "Crossroads Dental",
      "description": "Discover high-quality dental solutions tailored to your needs. We provide emergency dental care, Invisalign clear aligners, and more.",
      "email": "info@crossroadsdental.ca",
      "telephone": "(1) 234-5678",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "2384 Dundas St W ",
        "addressLocality": "Canada",
        "addressCountry": "CA",
        "addressRegion": "Toronto",
        "postalCode": "M6P 1W9"
      },
	  "geo": {
				"@type": "GeoCoordinates",
        "latitude": 43.655170,
        "longitude": -79.462510
			},
      
    }
    </script>